version: '3'
services:
  app:
    build: ./.docker/app
    environment:
      - TZ
      - LANG
      - DOMAIN
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
    volumes:
      - .:/var/www
    depends_on:
      - db
  web:
    image: nginx:1.15.6
    environment:
      - TZ
      - LANG
      - DOMAIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .credentials:/.credentials
      - .:/var/www
    depends_on:
      - app
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: