version: '3'
services:
  app:
    build: ./.docker/app
    env_file: .env
    volumes:
      - .:/var/www
    depends_on:
      - db
  web:
    build:
      context: ./.docker/web
      args:
        DOMAIN: $DOMAIN
        CREDENTIAL: $CREDENTIAL
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .credentials:/.credentials
      - .:/var/www
    depends_on:
      - app
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: